export const ORDERS_AMOUNT_CHANGED = 'ORDERS_AMOUNT_CHANGED';
export const ORDERS_CURRENCY_PAIR_CHANGED = 'ORDERS_CURRENCY_PAIR_CHANGED';
export const ORDERS_BOOK = 'ORDERS_BOOK';
export const ORDERS_BOOK_SUCCESS = 'ORDERS_BOOK_SUCCESS';
export const ORDERS_BOOK_ERROR = 'ORDERS_BOOK_ERROR';
